# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bQlEC61T1YpmLnBsw9cc9Z_4hlsl2zq
"""

# =============================================================
# APP STREAMLIT – PRESUPUESTO DE CONSTRUCCIÓN COMPLETO
# =============================================================

import streamlit as st
import pandas as pd
import numpy as np
import io

# -------------------------------------------------------------
# 1. CONFIGURACIÓN DE LA PÁGINA
# -------------------------------------------------------------
st.set_page_config(
    page_title="Presupuesto de Construcción",
    layout="wide"
)

st.title("🧱 TERRAKON GROUP: Presupuesto de Construcción")
st.write("Cálculo automático de ACU, AIU, IVA y reportes.")

# -------------------------------------------------------------
# 2. PLANTILLA BASE
# -------------------------------------------------------------
plantilla_cols = [
    "capitulo", "codigo", "descripcion", "tipo", "unidad",
    "cantidad", "rendimiento_unidad", "precio_unitario",
    "factor_merma", "cuadrilla_mo", "rendimiento_cuadrilla"
]

plantilla_ejemplo = pd.DataFrame([
    ["EARTHWORK", "T01", "Excavación manual", "mano_obra", "m3", 120, 1, 25000, 1.00, "obrero", 2.5],
    ["EARTHWORK", "M01", "Retiro de material", "equipo", "m3", 120, 1, 18000, 1.00, "", 1],
    ["CONCRETO", "M10", "Cemento 42.5kg", "material", "saco", 300, 1, 25000, 1.05, "", 1],
    ["CONCRETO", "M11", "Arena (m3)", "material", "m3", 12, 1, 120000, 1.03, "", 1],
    ["CONCRETO", "L01", "Oficial de construcción", "mano_obra", "h", 80, 1, 23000, 1.00, "oficial", 4.0],
], columns=plantilla_cols)

st.subheader("📄 Cargar Partidas")
archivo = st.file_uploader("Sube un archivo Excel con la estructura correcta", type=["xlsx"])

if archivo:
    df = pd.read_excel(archivo)
else:
    st.write("Usando plantilla de ejemplo.")
    df = plantilla_ejemplo.copy()

st.dataframe(df, use_container_width=True)

# -------------------------------------------------------------
# 3. PARÁMETROS AIU E IVA
# -------------------------------------------------------------
st.subheader("⚙️ Parámetros AIU e IVA")

col1, col2, col3, col4 = st.columns(4)

admin = col1.number_input("Administración (%)", 0.0, 1.0, 0.08)
imprev = col2.number_input("Imprevistos (%)", 0.0, 1.0, 0.03)
util = col3.number_input("Utilidad (%)", 0.0, 1.0, 0.10)
iva_pct = col4.number_input("IVA (%)", 0.0, 1.0, 0.19)

aiu_porcent = {
    "administracion": admin,
    "imprevistos": imprev,
    "utilidad": util
}

# -------------------------------------------------------------
# 4. CÁLCULO DEL PRESUPUESTO
# -------------------------------------------------------------
st.subheader("🧮 Cálculos")

def calcular_costos(df, aiu_porcent, iva_pct):
    df = df.copy()

    # Costo directo base
    df["costo_directo"] = (
        df["cantidad"] *
        df["precio_unitario"] *
        df["factor_merma"] /
        df["rendimiento_unidad"]
    )

    # MO por cuadrillas
    df["costo_mano_obra"] = np.where(
        df["tipo"] == "mano_obra",
        df["cantidad"] * df["precio_unitario"] / df["rendimiento_cuadrilla"],
        0
    )

    df["costo_total_partida"] = df["costo_directo"] + df["costo_mano_obra"]

    subt_cap = df.groupby("capitulo")["costo_total_partida"].sum().to_dict()
    subtotal_directo = df["costo_total_partida"].sum()

    aiu_valores = {k: subtotal_directo * v for k, v in aiu_porcent.items()}
    aiu_total = sum(aiu_valores.values())

    base_iva = subtotal_directo + aiu_total
    iva_valor = base_iva * iva_pct
    total_final = base_iva + iva_valor

    resumen = {
        "subtotales_capitulo": subt_cap,
        "subtotal_directo": subtotal_directo,
        "aiu_valores": aiu_valores,
        "aiu_total": aiu_total,
        "iva_valor": iva_valor,
        "total_final": total_final
    }

    return df, resumen


df_calc, resumen = calcular_costos(df, aiu_porcent, iva_pct)

st.write("### Resultados por partida:")
st.dataframe(df_calc, use_container_width=True)

# -------------------------------------------------------------
# 5. RESUMEN GENERAL
# -------------------------------------------------------------
st.subheader("📌 Resumen General")

st.write(f"**Subtotal directo:** ${resumen['subtotal_directo']:,.0f}")
st.write("**AIU:**")
for k, v in resumen["aiu_valores"].items():
    st.write(f"- {k}: ${v:,.0f}")

st.write(f"**Total AIU:** ${resumen['aiu_total']:,.0f}")
st.write(f"**IVA:** ${resumen['iva_valor']:,.0f}")
st.write(f"### ✅ TOTAL FINAL: ${resumen['total_final']:,.0f}")

# -------------------------------------------------------------
# 6. EXPORTAR A EXCEL
# -------------------------------------------------------------
st.subheader("⬇️ Descargar Reporte Excel")

def exportar_excel(df_calc, resumen):
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        df_calc.to_excel(writer, index=False, sheet_name="ACU")

        pd.DataFrame([
            {"concepto": "Subtotal directo", "valor": resumen["subtotal_directo"]},
            {"concepto": "AIU", "valor": resumen["aiu_total"]},
            {"concepto": "IVA", "valor": resumen["iva_valor"]},
            {"concepto": "Total final", "valor": resumen["total_final"]},
        ]).to_excel(writer, sheet_name="Resumen", index=False)

        pd.DataFrame([
            {"capitulo": c, "subtotal": v}
            for c, v in resumen["subtotales_capitulo"].items()
        ]).to_excel(writer, sheet_name="Capítulos", index=False)

    return output.getvalue()


excel_bytes = exportar_excel(df_calc, resumen)

st.download_button(
    label="📥 Descargar archivo Excel",
    data=excel_bytes,
    file_name="presupuesto_construccion.xlsx",
    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)

# End of app
